### ISSUE TITLE
我也不知道起啥标题，马上熄灯了，就这样吧

### ISSUE THREAD

**Issue by bismarckkk** [mijiaoqvq/SerialUltra#1]
* 引用难以对对象生命周期进行完整控制，跳过SerialUltra.h直接使用MessageProcessor可能会有意想不到的结果，此处可以使用`std::shared_ptr`共享指针来解决这个问题，共享指针管理一块有类型的基于引用计数的内存区域，在需要共享同一个变量时提供生命周期的安全性
https://github.com/mijiaoqvq/SerialUltra/blob/b0f79acb92321e58f400afa5ef8a70a4c1578dff/include/MessageProcessor/InputMessageProcessor.h#L30
* 这里还是应该用atomic<bool>，这个变量可能同时被主线程写且被read线程读，有冲突可能，C的原生类型支持用atomic修饰为原子变量（对小变量的一种内存冲突保护，由处理器提供支持）
https://github.com/mijiaoqvq/SerialUltra/blob/b0f79acb92321e58f400afa5ef8a70a4c1578dff/include/MessageProcessor/InputMessageProcessor.h#L31
* 应该尽可能减少“魔数”的使用，类似此处应该定义一个枚举，然后使用枚举值
https://github.com/mijiaoqvq/SerialUltra/blob/b0f79acb92321e58f400afa5ef8a70a4c1578dff/include/MessageProcessor/InputMessageProcessor.h#L43
* 这里的spinOnce是在模仿ros的api，它的含义是处理一次现在的数据，如果没有数据也可以不处理，不是一定要等到有数据为止，如果没有应该直接返回
https://github.com/mijiaoqvq/SerialUltra/blob/b0f79acb92321e58f400afa5ef8a70a4c1578dff/include/MessageProcessor/InputMessageProcessor.h#L147-L155

**Comment by mijiaoqvq** [comment]
其他的改了，但最后一个确实是没有数据直接返回啊

**Comment by bismarckkk** [comment]
> 其他的改了，但最后一个确实是没有数据直接返回啊

阿巴阿巴我人傻了，我的意思是不该用while

**Comment by mijiaoqvq** [comment]
可是不用while的话调用 `read()` 一次最多读取`MAX_READ_ONCE_CHAR`个字节，如果发送的数据包比较大就无法处理了。所以我想用len的值为0代表现有的数据都处理完了，然后我再跳出循环。
